# Generated by Django 4.0.1 on 2022-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('release_year', models.IntegerField(default=0)),
            ],
        ),
    ]
