# Generated by Django 4.0.1 on 2022-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviereviewapp", "0002_remove_movie_release_year_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(default=0),
        ),
    ]
