# Generated by Django 4.0.2 on 2022-03-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0008_review_a rating value is valid between 1 and 10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
