# Generated by Django 4.0.2 on 2022-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0009_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='metacritic_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='similars',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
