# Generated by Django 4.0.2 on 2022-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0010_movie_awards_movie_directors_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
